# Generated by Django 6.0.7 on 2026-08-23 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_dailyactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('first_step', 'First Step'), ('task_starter', 'Task Starter'), ('task_master', 'Task Master'), ('xp_hunter', 'XP Hunter'), ('level_up', 'Level Up'), ('streak_starter', 'Streak Starter'), ('week_warrior', 'Week Warrior')], max_length=50)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_user_achievement')],
            },
        ),
    ]
