# Generated by Django 6.0.7 on 2026-08-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_missionrewardclaim_questrewardclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='completed_tasks_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of tasks completed on this date.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_tasks_total',
            field=models.PositiveIntegerField(default=0, help_text='Historical number of tasks completed by the user.'),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_counted',
            field=models.BooleanField(default=False, help_text='Whether this task has already been counted toward historical completion progress.'),
        ),
    ]
