# Generated by Django 6.0.7 on 2026-09-12 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_dailyactivity_completed_tasks_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=20)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='Weekday numbers for weekly reminders. Monday=0 through Sunday=6.')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='tasks.task')),
            ],
            options={
                'ordering': ['next_run_at'],
            },
        ),
    ]
