"""
Django settings for To_Do_Solo project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

import os

from pathlib import Path


# ==========================================================
# PATHS
# ==========================================================

BASE_DIR: Path = Path(__file__).resolve().parent.parent


# ==========================================================
# SECURITY
# ==========================================================

SECRET_KEY: str = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-local-development-only"
)

DEBUG: bool = True

ALLOWED_HOSTS: list[str] = [
    "127.0.0.1",
    "localhost",
]


# ==========================================================
# APPLICATIONS
# ==========================================================

INSTALLED_APPS: list[str] = [

    # Django Apps

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Local Apps

    "apps.tasks",

]


# ==========================================================
# MIDDLEWARE
# ==========================================================

MIDDLEWARE: list[str] = [

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.locale.LocaleMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]


# ==========================================================
# URL CONFIGURATION
# ==========================================================

ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"


# ==========================================================
# TEMPLATES
# ==========================================================

TEMPLATES: list[dict] = [

    {
        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],

        },

    },

]


# ==========================================================
# DATABASE
# ==========================================================

DATABASES: dict[str, dict] = {

    "default": {

        "ENGINE":
            "django.db.backends.sqlite3",

        "NAME":
            BASE_DIR / "db.sqlite3",

    }

}


# ==========================================================
# PASSWORD VALIDATION
# ==========================================================

AUTH_PASSWORD_VALIDATORS: list[dict] = [

    {
        "NAME":
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.NumericPasswordValidator",
    },

]


# ==========================================================
# INTERNATIONALIZATION
# ==========================================================

LANGUAGE_CODE: str = "en"

TIME_ZONE: str = "Asia/Baghdad"

USE_I18N: bool = True

USE_TZ: bool = True


LANGUAGES: list[tuple[str, str]] = [

    ("en", "English"),

    ("ar", "Arabic"),

]


LOCALE_PATHS: list[Path] = [

    BASE_DIR / "locale",

]


# ==========================================================
# STATIC FILES
# ==========================================================

STATIC_URL: str = "static/"

STATICFILES_DIRS: list[Path] = [

    BASE_DIR / "static",

]

STATIC_ROOT: Path = BASE_DIR / "staticfiles"


# ==========================================================
# MEDIA FILES
# ==========================================================

MEDIA_URL: str = "media/"

MEDIA_ROOT: Path = BASE_DIR / "media"


# ==========================================================
# DEFAULT PRIMARY KEY
# ==========================================================

DEFAULT_AUTO_FIELD: str = (
    "django.db.models.BigAutoField"
)


# ==========================================================
# AUTHENTICATION
# ==========================================================

LOGIN_URL = "tasks:login"

LOGIN_REDIRECT_URL = "tasks:dashboard"

LOGOUT_REDIRECT_URL = "tasks:login"


# ==========================================================
# EMAIL
# ==========================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = "smtp.gmail.com"

EMAIL_PORT = 587

EMAIL_USE_TLS = True


EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    ""
)

EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    ""
)

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
